### PR TITLE
[menu-bar] use SF Symbols icons in Build section items

### PR DESCRIPTION
**Pull request by Simek**
# Why

We can use SF Symbols as menu item icons, which should align UI more with native side, and we can spare few KBs of assets.

# How

Add the `SFIcon` helper component (SF Symbols have the variable width, that why we need to wrap and align them), use it inside Build sections items, remove old assets.

# Preview
Screenshot 2023-08-08 at 20 01 53
Screenshot 2023-08-08 at 20 01 37

### CODE REVIEW

**Review by gabrieldonadel — APPROVED** [review]
LGTM, let me just fix these conflicts for you

**Comment by gabrieldonadel** [comment]
It seems that this does not work on computers that don't have the SF Symbols app installed

Screenshot 2023-08-09 at 00 42 27

**Comment by gabrieldonadel** [comment]
I'll have to revert this for tomorrow's launch but feel free to reopen this PR including the fix

**Comment by Simek** [comment]
Nice catch! Wonder if the same issue exist for Native version of the component we have. If not, we probably can improve the component a bit to accept mode and color (https://developer.apple.com/design/human-interface-guidelines/sf-symbols#Rendering-modes) and then use it for menu options. But the older icons are also fine for now, this is definetely not a release blocker. 😉

**Pull request merged**
